### ISSUE TITLE
Criar lista de emails

### ISSUE THREAD

**Issue by psychomantys** [psychomantys/epic-rpg-editor#3]
Queria criar uma lista de emails... Mas o github não tem nativamente isso :.

Gosto do formato do sourceforge, que usa 3 lista(mais ou menos....):
- geral
  - Discussão de usuários
  - Assuntos diversos e todo o resto em geral
- dev
  - Lista para assuntos de desenvolvimento diretamente
- news
  - Lista para divulgação de novas versões
  - Empacotadores ficam esperando aqui

Se não tiver nenhuma ideia a mais, vou criar no google mesmo e uma lista pelo menos inicialmente.

**Comment by vinipsmaker** [comment]
Depois de criar a lista, cadastre no gmane: http://gmane.org/subscribe.php

**Comment by dielsonsales** [comment]
O sourceforge tem alguma outra vantagem?

**Comment by vinipsmaker** [comment]
> O sourceforge tem alguma outra vantagem?

Propagandas em todos os emails.

**Comment by psychomantys** [comment]
@dielsonsales Nenhuma a mais que eu lembre, faz tempo que eu não uso ele. Ele tem listas de email, mas sõ isso a mais mesmo. Creio que o github não quer as listas mesmo.
